application: youtrack-slide
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico))

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: .*
  script: main.py
